### PR TITLE
asciidoc: add cleanspaces option to remove extra spaces

### PR DESCRIPTION
**Pull request by jnavila**
Extra spaces are removed in no-wrap segments, so that the output conforms to English typography rules.

This fixes GitHub #464

### CODE REVIEW

**Comment by mquinson** [comment]
Hello Jean-Noël, thanks for this patch.

maybe the cleanup should be the default behavior for new users, don't you think?

I'm not completely decided, but it seems somehow better.

Mt

**Comment by jnavila** [comment]
I don't grasp the idea of "the default behavior for new users". Do you mean that we should somehow differentiate between creating the pot file and updating it? How can we do it, and save the actual state of the option?

For sure, for existing translation project, it is critical to retain the behavior of unset cleanspaces, unless the project manager actively enables it.

**Comment by jnavila** [comment]
OK, so your option is the harsh one :laughing: ... Being the main developer of this feature and being plagued with this is issue, I know that this can be cumbersome to change a lot of segments, only for some whitespace issues.

I don't know how to intend to warn user about this compatibility breakage. I would at least issue a warning when such issue is detected and extra whitespaces are detected and removed. So maybe, this option should be activated by default, generating a warning. When the option is set to true or false, the warning would disappear.

Personally, I understand your point: a sane behavior for new projects, but I don't like at all breaking the increasing number of projects relying on po4a. In any case, it would be a breaking change that needs to be strongly advertised.

**Comment by jnavila** [comment]
Please note that right now, the patch cleans up the original string of its extra spaces but does not post process the translated string.

**Comment by mquinson** [comment]
Thanks a lot @jnavila, I merged this as is. You are right about not upsetting the translators by default.

**Pull request merged**
