### PR TITLE
New module for Gemtext format

### PR DESCRIPTION
**Pull request by gemmaro**
Hello,

This is a new module for the Gemtext format.
This plain text format is mainly used by the [Gemini protocol][gemini].
I have used this module to translate some of their documents and it seems to work.

Thank you,
gemmaro.

[gemini]: https://geminiprotocol.net/

### CODE REVIEW

**Comment by mquinson** [comment]
Wonderful. Thanks a lot, merged.

**Comment by kloczek** [comment]
Is it possible to release new version because merge of this PR? 🤔

**Comment by mquinson** [comment]
we gonna release soon, yes

**Comment by kloczek** [comment]
Thank you very much 👍

**Pull request merged**
