### PR TITLE
asciidoc: follow up on #343, disable tablecells for non-PSV tables

### PR DESCRIPTION
**Pull request by jnavila**
In such case, the table is processed as a simple verbatim text block.

Please note that I added a warning message, but running `./Build binpo` keeps telling me that `po/bin/po4a.pot` is uptodate.

### CODE REVIEW

**Comment by mquinson** [comment]
Great, thanks!

**Comment by jnavila** [comment]
Can you check why po4a.pot does not update?

**Comment by mquinson** [comment]
I'm not sure. I usually do `./Build postats` to update the POT files, and then I commit the POT files and revert the PO ones. I prefer to have weblate doing the msgmerge, even if I forgot what could possibly go wrong if I do it manually.

I think that this is not a big deal, as I don't mind updating the POT files on need. I feel too lazy to go and fix the generation scripts instead... I hope you don't mind

**Comment by jnavila** [comment]
Oh, ok. `postats` then.

**Pull request merged**
