### PR TITLE
Add YAML file support

### PR DESCRIPTION
**Pull request by bexelbie**
This implements YAML parsing with YAML::Tiny

### CODE REVIEW

**Comment by bexelbie** [comment]
I'd like to not merge this yet either, but I did want to submit it for feedback.

It adds a dependency on YAML::Tiny.  I suspect it is packaged for Debian.

**Comment by mquinson** [comment]
Hello,

why exactly you don't want to get this merged yet? It sounds very good to me, don't you think? I do not see what to add...

**Comment by bexelbie** [comment]
I was hoping to beat it up a bit more.  At this point, let's merge it and I'll patch it if I find anythign down the road.

**Comment by mquinson** [comment]
Yes, exactly. You have a decent code, a decent documentation, some decent tests, so you're more than ready for the big day. Let's fix the bug when they appear afterward (if they do) instead of staring at the code to see eventual future issues :)

**Pull request merged**
