### PR TITLE
Add keyvalue option to not wrap key:value paras

### LINKED ISSUE #8: Key/Value Pairs should be treated as verbatim
Many static site generators, amongst other things, require a set of header information at the top of the file such as:

```
Title: Some title
Date: Some date

lorem ipsum ...

foo bar baz ...
```

We should be able to optionally allow any paragraph formatted as key:value to be treated as verbatim.  I have a potential fix (needs tests) here: https://github.com/bexelbie/po4a/tree/keyvalue_text

### PR DESCRIPTION
**Pull request by bexelbie**
Fixes #8

Signed-off-by: Brian (bex) Exelbierd <bex@pobox.com>

### CODE REVIEW

**Comment by mquinson** [comment]
Thanks for the test case, too!

**Comment by bexelbie** [comment]
Any further feedback on the test case is very welcome!

**Comment by mquinson** [comment]
My feeling is that Markdown should be split in another format, separated from Text. There is already enough Markdown dialects that you don't want to take all of them as options to the Text module.

But that's not a strong feeling either ;)

**Comment by bexelbie** [comment]
I agree with your comment about splitting the formats.  I don't have time to work on it right now though :(

**Comment by mquinson** [comment]
We should probably open a new issue to keep track of this, don't you think  ?

**Pull request merged**
