### PR TITLE
Fix docbook bookinfo

### PR DESCRIPTION
**Pull request by mquinson**
New version of the PR #145

### CODE REVIEW

**Comment by mquinson** [comment]
Hello @osamuaoki, this passes the test and is almost ready to be merged in the trunk. Could you please consider adding a test experiencing the bookinfo tag?

Many thanks for your work,

**Comment by bexelbie** [comment]
The appveyor tests look like they are timing out - but I can't find evidence of that.

**Comment by mquinson** [comment]
Let's forget about AppVeyor here: it never worked for us in the past. It should be fixed, but that's definitely not blocking for this PR.

**Comment by osamuaoki** [comment]
I realized that polishing regex fix the issue.

@{$self->{TT}{doc_out}} = map { split /(?<=\n)/, $_ } @{$self->{TT}{doc_out}};

The lookbehind is the trick.to use!

Anyway, I am reading code more to make safer change with test case soon.

**Comment by mquinson** [comment]
Hello @osamuaoki , this PR can now be closed, right?

Thanks for your help,

**Comment by osamuaoki** [comment]
Please close this since correct patch is already accepted.  Merci!

**Comment by mquinson** [comment]
thanks!

**Pull request closed without merging**
