### PR TITLE
fix the fix for #416 :-)

### PR DESCRIPTION
**Pull request by jnavila**
This takes into account:

 * variables in the index entry
 * quoted index entries

### CODE REVIEW

**Comment by jnavila** [comment]
@suddenfall Can you test this PR. Your issues should be covered.

**Comment by suddenfall** [comment]
Hi,

I have found another issue with ordered and unorded lists (https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/, https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/).

The concealed index term is inserted before the list item identify. Following example fails:

```
== A title
Some text here.

* (((Mode,Windows)))Windows mode: Some more text.
* (((Mode,Linux)))Linux mode: Some other text.
** (((Mode,Custom)))Custom mode: Got out of text.
- (((Mode,Wild)))Wild mode: Explains itself.

New text here.

. (((Mode,Windows)))Windows mode: Some more text.
. (((Mode,Linux)))Linux mode: Some other text.
.. (((Mode,Custom)))Custom mode: Got out of text.
. (((Mode,Wild)))Wild mode: Explains itself.

Another new text here.

1. (((Mode,Windows)))Windows mode: Some more text.
2. (((Mode,Linux)))Linux mode: Some other text.
    a. (((Mode,Custom)))Custom mode: Got out of text.
4. (((Mode,Wild)))Wild mode: Explains itself.
```
For exampe `* (((Mode,Windows)))Windows mode: Some more text.` becomes to `(((Mode,Windows)))* Windows mode: Some more text.` and is now not anymore a list item.

**Comment by jnavila** [comment]
Thank you for this thorough testing.  I pushed a few more commits that should fix the issues you raised:
 
* index entries in lists
* index entries in titles
* management of checklists (this one is not specific to index entries, but is related to list management)

Let me know if it for your documents.

**Comment by mquinson** [comment]
@jnavila please tell me when you want me to review these changes.
Thx,

**Pull request merged**
